apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: custom-device-plugin
  namespace: kube-system
  labels:
    app: custom-device-plugin
spec:
  selector:
    matchLabels:
      app: custom-device-plugin
  template:
    metadata:
      labels:
        app: custom-device-plugin
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: device-plugin
          image: kaynwong/custom-device-plugin:latest
          imagePullPolicy: IfNotPresent
#          args:
#            - --resource-name=nvidia.com/gpu
          resources:
            limits:
              memory: 200Mi
          volumeMounts:
            - name: device
              mountPath: /etc/custom-dev
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
          securityContext:
            privileged: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: device
          hostPath:
            path: /etc/custom-dev
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins